### ISSUE TITLE
Services are not synchronized without a specific Dependency

### ISSUE THREAD

**Issue by krjensen** [istio-ecosystem/admiral#145] opened 2020-09-24 11:11 UTC
After deploying a base Admiral setup for two k8s clusters, nothing is synced between clusters.
When I create a specific `Dependency` the sync works

```
---
apiVersion: admiral.io/v1alpha1
kind: Dependency
metadata:
  name: dependency
  namespace: admiral
spec:
  source: Service-a
  identityLabel: identity
  destinations:
    - Service-b
```

Reading the documentation it states:
"Dependency is optional and a missing dependency for a service will result in an Istio configuration for that service pushed to all clusters."

So I would expect all services to be synchronized across all clusters, when no Dependency is created. 

Is also says her: https://github.com/istio-ecosystem/admiral/blob/master/docs/Architecture.md
"If the wild card and specific dependency object are both present any service not matching a specific rule will be sync to all clusters"

But no information about, how to create such a wild card dependency...

/Kristian

**Comment by aattuluri** [comment] 2020-09-25 02:57
@krjensen Thanks for reporting, this is a duplicate of https://github.com/istio-ecosystem/admiral/issues/85, please upvote this issue so we can prioritize that for 1.2 release.

**Closed by aattuluri** 2020-09-25 02:57 UTC
Labels: bug

**Comment by krjensen** [comment] 2020-09-25 04:47
Ah sorry for duplicating the issue.
